#!/bin/csh
# this script calculate pCFC using NCO
#
# Qing Li, 141212

if ( $#argv != 2 ) then
cat << EOF
USAGE:
	cesm_ocean_pcfc_get [case name] [year]
EOF
exit -1;
endif

set casename = $1
set sty = `printf %04d $2`

# set outdir, nco_util
source ./set_env

set pophist = ${outdir}/${casename}/${casename}.pop.avgh.${sty}.${sty}.nc

if ( ! -e ${pophist} ) then
	cesm_ocean_avg $1 $2 $3 1
endif
if ( $? != 0 ) then
	echo "No POP History File"
	exit -1;
endif

echo "Input file: ${pophist}"

foreach cfc ( pcfc11 pcfc12 )
	set file_out = ${outdir}/${casename}/${casename}.${cfc}.${sty}.${sty}.nc
	if ( -e ${file_out} ) then
		rm ${file_out}
	endif
	ncap2 -A -v -S ${nco_util}/${cfc}.nco ${pophist} ${file_out}
end

