#!/bin/csh
#
# This script get annual averaged history files from
# monthly output
#
# Qing Li, 20150713
#

if ( $#argv != 2 ) then
cat << EOF
USAGE:
	cesm_ocean_mon2ann [case name] [year]
EOF
exit -1;
endif

set casename	= $1
@ yrini = $2

# set datadir, outdir, workdir
source ./set_env

set prefixi	= ${casename}.pop.h
set yrini_str	= `printf %04d $yrini`
set outfile	= ${prefixi}.${yrini_str}.nc

echo " Year ${yrini_str} "

cd $datadir
ncra -O -h ${prefixi}.${yrini_str}-??.nc ${outfile}

